catalog/urls.py
from catalog.views import AuthorCreateView, AuthorDeleteView, AuthorDetailView, AuthorListView, AuthorUpdateView, \
    author_info, authors_list, book_info, books_list, index, publisher_info, publishers_list, stores_info, stores_list

from django.urls import path

app_name = 'catalog'
urlpatterns = [
    path('', index, name="index"),
    path('books/', books_list, name='books'),
    path('books/<int:id>/', book_info, name='books_info'),
    path('authors/', authors_list, name="authors"),
    path('authors/<int:id>/', author_info, name='author_info'),
    path('stores/', stores_list, name="stores"),
    path('stores/<int:id>', stores_info, name="stores_info"),
    path('publishers/', publishers_list, name='publishers'),
    path('publishers/<int:pk>', publisher_info, name='publisher_info'),
    path('authors/create_author', AuthorCreateView.as_view(), name='create_author'),
    path('authors/<int:pk>/update/', AuthorUpdateView.as_view(), name='update_author'),
    path('authors/<int:pk>/delete/', AuthorDeleteView.as_view(), name='delete_author'),
    path('authors/pagination/', AuthorListView.as_view(), name='pagination_author'),
    path('authors/pagination/<int:pk>/detail/', AuthorDetailView.as_view(), name='detail_author')
]

hillel_django_project1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

catalog/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} {self.surname}"


class Store(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name} | {self.address}"


class Publisher(models.Model):
    name = models.CharField(max_length=100)
    year = models.IntegerField()
    store = models.OneToOneField(Store, primary_key=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    publisher = models.ManyToManyField(Publisher)
    pubdate = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} | {self.price} | {self.author}"

catalog/views.py
from catalog.models import Author, Book, Publisher, Store

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Avg, Count, Max, Min
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView


def index(request):
    return render(request, 'catalog/index.html')


def books_list(request):
    info = Book.objects.all().aggregate(Avg('price'), Max('price'), Min('price'), Count('title'), Max('pages'),
                                        Min('pages'))
    book_list = Book.objects.select_related('author').all()
    books = []
    for book in book_list:
        books.append({'id': book.id, 'title': book.title, 'author': book.author.surname})
    return render(request, 'catalog/books.html', {'books': books, 'info': info})


def book_info(request, id):  # noqa:A002
    book = Book.objects.select_related('author').get(id=id)
    publisher = Publisher.objects.prefetch_related('book_set__publisher').filter(book=id)
    return render(
        request,
        'catalog/book_info.html',
        {'id': book.id,
         'title': book.title,
         'pages': book.pages,
         'price': book.price,
         'pubdate': book.pubdate,
         'author': book.author.surname,
         'author_id': book.author.id,
         'publisher': publisher,
         'publisher_id': book.publisher.name
         }
    )


def authors_list(request):
    authors = Author.objects.all().annotate(count=Count('surname'))
    return render(request, 'catalog/authors.html', {'authors': authors, })


def author_info(request, id):  # noqa: A002
    author = Author.objects.get(id=id)
    book_author = Book.objects.select_related('author').filter(author_id=id)
    return render(
        request,
        'catalog/author_info.html',
        {'id': author.id,
         'name': author.name,
         'surname': author.surname,
         'country': author.country,
         'books': book_author
         }
    )


def stores_list(request):
    store_list = Store.objects.select_related('publisher').all()
    stores = []
    for store in store_list:
        count = Book.objects.prefetch_related('publisher__store').filter(publisher__name=store.publisher.name). \
            annotate(count=Count('title'))

        stores.append({'id': store.id, 'name': store.name, 'address': store.address, 'publisher': store.publisher.name,
                       'count': count})
    return render(request, 'catalog/stores.html', {'stores': stores, })


def stores_info(request, id):  # noqa: A002
    store = Store.objects.prefetch_related('publisher').get(id=id)
    books = Book.objects.prefetch_related('publisher').filter(publisher__name=store.publisher.name)
    return render(request,
                  'catalog/stores_info.html',
                  {'id': store.id,
                   'name': store.name,
                   'address': store.address,
                   'publisher': store.publisher.name,
                   'books': books
                   }
                  )


def publishers_list(request):
    publisher_list = Publisher.objects.select_related('store').all()
    pub_list = []
    for publisher in publisher_list:
        books = Book.objects.prefetch_related('publisher').filter(publisher__name=publisher.name). \
            aggregate(Avg('price'))
        pub_list.append(
            {'name': publisher.name, 'store': publisher.store.name, 'pk': publisher.pk, 'books': books})
    return render(request, 'catalog/publishers.html', {'pub_list': pub_list, })


def publisher_info(request, pk):
    publisher = Publisher.objects.get(pk=pk)
    books = Book.objects.prefetch_related('publisher').filter(publisher__name=publisher.name)
    return render(request,
                  'catalog/publisher_info.html',
                  {'id': publisher.pk,
                   'name': publisher.name,
                   'store': publisher.store,
                   'year': publisher.year,
                   'books': books
                   }
                  )


class AuthorCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Author
    fields = ['name', 'surname', 'country']
    template_name = 'catalog/author_form.html'
    success_message = "New author was created"
    success_url = reverse_lazy('catalog:authors')


class AuthorUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Author
    fields = ['name', 'surname', 'country']
    template_name = 'catalog/update_author.html'
    success_message = "Author was updated"
    success_url = reverse_lazy('catalog:authors')


class AuthorDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Author
    fields = ['name', 'surname', 'country']
    template_name = 'catalog/delete_author.html'
    success_message = "Author was deleted"
    success_url = reverse_lazy('catalog:authors')


class AuthorListView(ListView):
    model = Author
    paginate_by = 5
    template_name = 'catalog/pagination_author.html'


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'catalog/detail_author.html'

catalog/templates/catalog/create_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create author</title>
</head>
<body>
    <h1>Create new author</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
    <ul><a href="{% url 'catalog:authors' %}">Back to author list</a></ul>
</form>
</body>
</html>

templates/catalog/author_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create author</title>
</head>
<body>
    <h1>Create new author</h1>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

    <input type="submit" value="Save">
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
    <ul><a href="{% url 'catalog:authors' %}">Back to author list</a></ul>

</body>
</html>

templates/catalog/author_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author information</title>
</head>
<body>
<ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
<ul><a href="{% url 'catalog:authors' %}">Back to the list of authors</a></ul>
<ul><a href="{% url 'catalog:update_author' pk=id %}">Update this author</a></ul>
<ul><a href="{% url 'catalog:delete_author' pk=id %}">Delete this author</a></ul>
<h1>Information about author:</h1>
    <ul>ID: {{ id }}</ul>
    <ul>Name: {{ name }} {{ surname }}</ul>
    <ul>Country: {{ country }}</ul>
<h2>Books written by {{ surname }}: </h2>
    {% for obj in books %}
            <ul><a href="{% url 'catalog:books_info' id=obj.id %}">{{ obj.id }} "{{ obj.title }}"</a></ul>
    {% endfor %}

</body>

</html>

templates/catalog/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
        <h1>Count of authors: {{ authors.count }}</h1>
       <h2>List of authors</h2>
       <ul>
            {% for obj in authors %}
                <li><a href="{% url 'catalog:author_info' id=obj.id %}">{{ obj.name }} {{ obj.surname }}</a></li>
            {% endfor %}
        </ul>
    <ul><a href="{% url 'catalog:create_author' %}">Create author</a></ul>
    <ul><a href="{% url 'catalog:pagination_author' %}">Pagination of authors</a></ul>
</body>
</html>

templates/catalog/book_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book information</title>
</head>
<body>

<h1>Information about book:</h1>
    <ul>ID: {{ id }}</ul>
    <ul>Title: {{ title }}</ul>
    <ul><a href="{% url 'catalog:author_info' id=author_id %}">Author: {{ author }}</a></ul>
    <ul>Publishers:</ul>
        {% for obj in publisher %}
            <ul><a href="{% url 'catalog:publisher_info' pk=obj.pk %}">{{ obj.name }}</a></ul>
        {% endfor %}
    <ul>Price: {{ price }}</ul>
    <ul>Pages: {{ pages }}</ul>
    <ul>Pubdate: {{ pubdate }}</ul>
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
    <ul><a href="{% url 'catalog:books' %}">Back to the list of books</a></ul>
</body>
</html>

templates/catalog/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books</title>
</head>
<body>
    <h1>Information:</h1>
    <li>Count of books: {{ info.title__count }}</li>
    <li>Avg price: {{info.price__avg}}</li>
    <li>Max price: {{ info.price__max }}</li>
    <li>Min price: {{ info.price__min }}</li>
    <li>Max pages: {{ info.pages__max }}</li>
    <li>Min pages: {{ info.pages__min }}</li>
   <h2>List of books</h2>
   <ul>
        {% for obj in books %}
            <li><a href="{% url 'catalog:books_info' id=obj.id %}">{{ obj.id }} "{{ obj.title }}" {{ obj.author }}</a></li>
        {% endfor %}
    </ul>
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
</body>
</html>

templates/catalog/delete_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete author</title>
</head>
<body>
  <h1>Delete author</h1>
  <p>Are you sure you want to delete the author: {{ author }}?</p>
  <form action="" method="POST">
    {% csrf_token %}
      {{ form }}
    <input type="submit" value="Delete"><ul><a href="{% url 'catalog:authors' %}">Cancel</a></ul>
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
  </form>
</body>
</html>

templates/catalog/detail_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail author</title>
</head>
<body>
<h1>Detail about {{ object }}</h1>
    <ul>ID: {{ object.id }}</ul>
    <ul>Name: {{ object.name }} {{ object.surname }}</ul>
    <ul>Country: {{ object.country }}</ul>
<ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
<ul><a href="{% url 'catalog:authors' %}">Back to author list</a></ul>
</body>
</html>

templates/catalog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <h1> These links helps you to find book or authors or publishers or stores which you want!</h1>
    <p><a href="{% url 'catalog:books' %}">All books</a></p>
    <p><a href="{% url 'catalog:authors' %}">All authors</a></p>
    <p><a href="{% url 'catalog:publishers' %}">All publishers</a></p>
    <p><a href="{% url 'catalog:stores' %}">All stores</a></p>

</body>
</html>

templates/catalog/pagination_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pagination</title>
</head>
<body>
<h1>Pagination of authors</h1>
<ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
<ul><a href="{% url 'catalog:authors' %}">Back to author list</a></ul>
{% block pagination %}
    {% if is_paginated %}
        {% for i in paginator.page_range %}
        <ul><a href={{ request.path }}?page={{ i }}></a></ul>
        {% endfor %}
    <div class="pagination">
     {% for obj in author_list %}
        <li><a href="{% url 'catalog:detail_author' pk=obj.id %}">{{ obj.name }} {{ obj.surname }}</a></li>
        {% endfor %}
        <span class="page-links">
         <span class="page-current">
          Page {{ page_obj.number }} or {{ page_obj.paginator.num_pages }}
         </span>
        {% if page_obj.has_previous %}
            <ul><a href={{ request.path }}?page={{ page_obj.previous_page_number }}>Previous</a></ul>
        {% endif %}
         {% if page_obj.has_next%}
            <ul><a href={{ request.path }}?page={{ page_obj.next_page_number }}>Next</a></ul>
        {% endif %}
      </span>
    </div>
    {% endif %}
{% endblock %}
</body>
</html>

templates/catalog/publisher_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Publisher information</title>
</head>
<body>

<h1>Information about publisher:</h1>
    <ul>ID: {{ id }}</ul>
    <ul>Name: {{ name }}</ul>
    <ul>Year: {{ year }}</ul>
<ul><a href="{% url 'catalog:stores_info' id=store.id %}">Store: {{ store.name }}</a></ul>
    <ul>Books:</ul>
        {% for obj in books %}
            <ul><a href="{% url 'catalog:books_info' id=obj.id %}">{{ obj.id }} "{{ obj.title }}"</a></ul>
    {% endfor %}
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
    <ul><a href="{% url 'catalog:publishers' %}">Back to the list of publishers</a></ul>
</body>
</html>

templates/catalog/publishers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Publishers</title>
</head>
<body>
   <h1>List of publishers:</h1>
   <ul>
        {% for obj in pub_list%}
            <li><a href="{% url 'catalog:publisher_info' pk=obj.pk %}"> {{ obj.name }}</a></li>
            <ul>Store: {{ obj.store }}</ul>
            <ul>Average price of books: {{ obj.books.price__avg }}</ul>
        {% endfor %}
    </ul>
   <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
</body>
</html>

templates/catalog/stores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stores</title>
</head>
<body>

   <h1>List of stores</h1>
   <ul>
        {% for obj in stores %}
            <li><a href="{% url 'catalog:stores_info' id=obj.id %}">{{ obj.name }}</a></li>
            <ul>Address: {{ obj.address }}</ul>
            <ul>Publisher: {{ obj.publisher }}</ul>
            <ul>Count of books: {{ obj.count.count }}</ul>
        {% endfor %}
    </ul>
   <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
</body>
</html>

templates/catalog/stores_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store information</title>
</head>
<body>

<h1>Information about store:</h1>
    <ul>ID: {{ id }}</ul>
    <ul>Name: {{ name }}</ul>
    <ul>Address: {{ address }}</ul>
    <ul>Publisher: {{ publisher }}</ul>
    <ul>Books:</ul>
        {% for obj in books %}
            <ul><a href="{% url 'catalog:books_info' id=obj.id %}">{{ obj.id }} "{{ obj.title }}"</a></ul>
    {% endfor %}
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
    <ul><a href="{% url 'catalog:stores' %}">Back to the list of stores</a></ul>
</body>
</html>

templates/catalog/update_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload author</title>
</head>
<body>
<h1>Upload author</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>Are you sure you want to update the author: {{ author }}?</p>
    <input type="submit" value="Update"><ul><a href="{% url 'catalog:authors' %}">Cancel</a></ul>
    <ul><a href="{% url 'catalog:index' %}">Back to main menu</a></ul>
</form>
</body>
</html>